
name: Update Github Stats

on:
  schedule:
    - cron: "47 2 * * *"
    
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install requirements
      - name: Install requirements
        run: |
          npm install
          
      - name: Github Configurations
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "action@github.com"
          git pull
          
      - name: Update Template
        run: |
          node updater.js ${{ github.repository_owner }} dracula
        env:
          GHT: ${{ secrets.GHT }}
          
      # Commiting
      - name: commiting changed svg template
        run: |
          git add .
          git commit -m "Github Stats updated ðŸŽ‰" || echo
          git push
